INSERT INTO `pcm_helpdeskpro_emails` (`id`, `email_key`, `email_message`) VALUES
(1, 'new_ticket_admin_email_subject', '[[CATEGORY_TITLE] - #[TICKET_ID]](New) [TICKET_SUBJECT]'),
(2, 'new_ticket_admin_email_body', '<p>User <strong>[NAME]</strong> has just submitted support ticket #[TICKET_ID]</p>\r\n<p><strong>[TICKET_SUBJECT]</strong></p>\r\n<p>[TICKET_MESSAGE]</p>\r\n<p><a href=\"[FRONTEND_LINK]\">You can click here to view the ticket from front-end</a></p>\r\n<p><a href=\"[BACKEND_LINK]\">You can click here to view the ticket from back-end of your site</a></p>'),
(3, 'new_ticket_user_email_subject', '[[CATEGORY_TITLE]]Ticket #[TICKET_ID] received'),
(4, 'new_ticket_user_email_body', '<p>Dear <strong>[NAME]</strong></p>\r\n<p>We received your support request for ticket #[TICKET_ID]. Our support staff will check and reply you within 24 hours. Below are detail of your support ticket:</p>\r\n<p><strong>[TICKET_SUBJECT]</strong></p>\r\n<p>[TICKET_MESSAGE]</p>\r\n<p><a href=\"[FRONTEND_LINK]\">You can click here to view the ticket</a></p>\r\n<p><a href=\"[FRONTEND_LINK_WITHOUT_LOGIN]\">You can also click here to view the ticket without having to login</a></p>'),
(5, 'ticket_updated_admin_email_subject', '[[CATEGORY_TITLE] - #[TICKET_ID]](Updated) [TICKET_SUBJECT]'),
(6, 'ticket_updated_admin_email_body', '<p>User [NAME] has just added a comment to ticket #[TICKET_ID] :</p>\r\n<p>[TICKET_COMMENT]</p>\r\n<p><a href=\"[FRONTEND_LINK]\">You can click here to view the ticket from front-end</a></p>\r\n<p><a href=\"[BACKEND_LINK]\">You can click here to view the ticket from back-end of your site</a></p>'),
(7, 'ticket_updated_user_email_subject', '[[CATEGORY_TITLE] - #[TICKET_ID]](Updated) [TICKET_SUBJECT]'),
(8, 'ticket_updated_user_email_body', '<p>Dear <strong>[NAME]</strong></p>\r\n<p>User <strong>[MANAGER_NAME]</strong> has just added a comment to ticket #<strong>[TICKET_ID]</strong>:</p>\r\n<p>[TICKET_COMMENT]</p>\r\n<p><a href=\"[FRONTEND_LINK]\">You can click here to view the ticket</a></p>\r\n<p><a href=\"[FRONTEND_LINK_WITHOUT_LOGIN]\">You can also click here to view the ticket without having to login</a></p>'),
(9, 'ticket_assiged_email_subject', 'New Ticket assignment'),
(10, 'ticket_assiged_email_body', '<p>Dear [STAFF_NAME]</p>\r\n<p>[MANAGER_NAME] has just assigned a new ticket #[TICKET_ID] to you. Please login to your account, check and work on the ticket.</p>');
